name: Build Dev Branches

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - beta
      - staging
      - production
    paths:
      - 'games/**'

jobs:
  push:
    name: "aioegg:${{ github.ref_name }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./games/carbon
          file: ./games/carbon/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/aioegg:${{ github.ref_name }}